greeter.hyprland.conf
# Configure your monitors here if needed

# Execute the ctOS greeter in greetd mode
exec-once = CTOS_MODE=greetd quickshell --path /opt/ctos/Greeter

animations {
    # Remove launch transitions (hyprland zoom effect)
    enabled = false
}

misc {
    # Hides the hyprland background
    background_color = rgba(0E0E0EFF)
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
