
workspace = 1, name:一
workspace = 2, name:二
workspace = 3, name:三
workspace = 4, name:四
workspace = 5, name:五
# workspace = 6, name:六

# Center single windows
workspace=r[2-5] w[t1], gapsout:150 150 150 150

# Productivity workspaces are scrolling
workspace = 2, layout:scrolling
workspace = 3, layout:scrolling


# hyprlang if HYPR_Z790E

workspace = 1, name:一, monitor:desc:ASUSTek COMPUTER INC PG27UQR R7LMQS169187, default=True, persistent:true
workspace = 2, name:二, monitor:desc:ASUSTek COMPUTER INC PG27UQR R7LMQS169187, persistent:true, layout=scrolling
workspace = 3, name:三, monitor:desc:ASUSTek COMPUTER INC PG27UQR R7LMQS169187, persistent:true
workspace = 4, name:四, monitor:desc:ASUSTek COMPUTER INC PG27UQR R7LMQS169187, persistent:true
workspace = 5, name:五, monitor:desc:ASUSTek COMPUTER INC ROG XG27UQR R4LMQS097007, persistent:true

# hyprlang endif

# hyprlang if HYPR_X13GEN5

workspace = 1, name:一, monitor:eDP-1, default=True, persistent:true
workspace = 2, name:二, monitor:eDP-1, persistent:true
workspace = 3, name:三, monitor:eDP-1, persistent:true
workspace = 4, name:四, monitor:eDP-1, persistent:true
workspace = 5, name:五, monitor:eDP-1, persistent:true

# hyprlang endif

# FIX
# I have now idea, why it does not work without :(
exec = hyprctl dispatch renameworkspace 1 "一"
exec = hyprctl dispatch renameworkspace 2 "二"
exec = hyprctl dispatch renameworkspace 3 "三"
exec = hyprctl dispatch renameworkspace 4 "四"
exec = hyprctl dispatch renameworkspace 5 "五"
# exec = hyprctl dispatch renameworkspace 6 "六"
