--
-- conf/colors.lua
-- Active color scheme, parsed from the Noctalia-generated palette so
-- other modules can reference theme colors without hardcoding them.
-- Source file is generated by Noctalia (and gitignored); we read it
-- rather than the generated noctalia.lua, which exposes no table.
--
-- Returns a flat table of bare hex strings, e.g. { primary = "98a0b3" }.
--

-------------------------------------------------------
-- Configuration
-------------------------------------------------------

local COLORS_FILE = (os.getenv("HOME") or "")
    .. "/.config/hypr/noctalia/noctalia-colors.conf"

-- Fallback palette, used if the generated file is missing.
local fallback = {
    primary        = "98a0b3",
    surface        = "1c1e21",
    secondary      = "8d8da5",
    error          = "fd4663",
    tertiary       = "938fa3",
    surface_lowest = "0e0f11",
}

-------------------------------------------------------
-- Helpers
-------------------------------------------------------

--- Parse `$name = rgb(hex)` / `rgba(hex)` lines into { name = "hex" }.
--- Alpha is dropped so values fit helpers expecting bare 6-digit hex.
--- @return table<string, string>
local function load()
    local f = io.open(COLORS_FILE, "r")
    if not f then return fallback end

    local colors = {}
    for line in f:lines() do
        local name, hex = line:match("^%s*%$([%w_]+)%s*=%s*rgba?%(([%x]+)%)")
        if name and hex then
            colors[name] = hex:sub(1, 6)
        end
    end
    f:close()

    -- Backfill anything Noctalia did not emit.
    for k, v in pairs(fallback) do
        if not colors[k] then colors[k] = v end
    end
    return colors
end

-------------------------------------------------------
-- Apply
-------------------------------------------------------

return load()
