# : Manager [[[

[mgr]
cwd = { fg = "#f1e0d0", italic=true }
preview_hovered = { underline = false }
# Tab
tab_active = { fg = "#332565", bg = "#cbbeff", bold = true }
tab_inactive = { fg = "#e7deff", bg = "#1d0d50" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffb04c", bg = "#ffb04c" }
marker_cut = { fg = "#ffddb2", bg = "#ffddb2" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#efbe79", bg = "#efbe79" }

# Count
count_copied = { fg = "#291800", bg = "#ffddb2" }
count_cut = { fg = "#291800", bg = "#ffddb2" }
count_selected = { fg = "#332565", bg = "#efbe79" }

# Border
# border_symbol = "|"
border_symbol = " "
border_style  = { fg = "#cbbeff" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#332565", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#cbbeff", fg = "#332565", bold = true }
normal_alt  = { bg = "#544432", fg = "#d9c3ac" }

# Select mode
select_main = { bg = "#d4c78e", fg = "#383006", bold = true }
select_alt  = { bg = "#544432", fg = "#d9c3ac" }

# Unset mode
unset_main = { bg = "#efbe79", fg = "#442b00", bold = true }
unset_alt  = { bg = "#544432", fg = "#d9c3ac" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#cbbeff", bg = "#42372c" }
progress_error = { fg = "#ffb4ab", bg = "#42372c" }

# Permissions
permissions_t = { fg = "#928137" }
permissions_w = { fg = "#b97516" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff9919" }
permissions_s = { fg = "#7845ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#cbbeff" }
active = { fg = "#efbe79", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#cbbeff" }
value = { fg = "#f1e0d0" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#cbbeff", bg = "#332565" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#cbbeff" }
title = {}
hovered = { fg = "#ffddb2", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#42372c" }
cand = { fg = "#cbbeff" }
rest = { fg = "#332565" }
desc = { fg = "#f1e0d0" }
separator = " ▶ "
separator_style = { fg = "#f1e0d0" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f1e0d0" }
run = { fg = "#f1e0d0" }
footer = { fg = "#383006", bg = "#d4c78e" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#efbe79" }
title_warn = { fg = "#cbbeff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", fg = "#93000a", italic=true },
    { name = "*", is = "exec", fg = "#ffdad6" },
    { name = "*", is = "link", dim=true, italic=true },

    # Fallback
    { name = "*", fg = "#f1e0d0" },
    { name = "*/", fg = "#cdcdcd" },
]

# : ]]]
