# : Manager [[[

[manager]
cwd = { fg = "#e6e1e9" }

# Tab
tab_active = { fg = "#34275e", bg = "#cdbdff", bold = true }
tab_inactive = { fg = "#e8deff", bg = "#1f1048" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff739c", bg = "#ff739c" }
marker_cut = { fg = "#ffd9e4", bg = "#ffd9e4" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#eeb8c9", bg = "#eeb8c9" }

# Count
count_copied = { fg = "#31111e", bg = "#ffd9e4" }
count_cut = { fg = "#31111e", bg = "#ffd9e4" }
count_selected = { fg = "#34275e", bg = "#eeb8c9" }

# Border
# border_symbol = "|"
border_symbol = " "
border_style  = { fg = "#cdbdff" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#34275e", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#cdbdff", fg = "#34275e", bold = true }
normal_alt  = { bg = "#48454e", fg = "#cac4cf" }

# Select mode
select_main = { bg = "#cbc3dc", fg = "#322e41", bold = true }
select_alt  = { bg = "#48454e", fg = "#cac4cf" }

# Unset mode
unset_main = { bg = "#eeb8c9", fg = "#492533", bold = true }
unset_alt  = { bg = "#48454e", fg = "#cac4cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#cdbdff", bg = "#3a383e" }
progress_error = { fg = "#ffb4ab", bg = "#3a383e" }

# Permissions
permissions_t = { fg = "#7762a4" }
permissions_w = { fg = "#d03d6b" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff4077" }
permissions_s = { fg = "#7d45ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#cdbdff" }
active = { fg = "#eeb8c9", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#cdbdff" }
value = { fg = "#e6e1e9" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#cdbdff", bg = "#34275e" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#cdbdff" }
title = {}
hovered = { fg = "#ffd9e4", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3a383e" }
cand = { fg = "#cdbdff" }
rest = { fg = "#34275e" }
desc = { fg = "#e6e1e9" }
separator = " ▶ "
separator_style = { fg = "#e6e1e9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e6e1e9" }
run = { fg = "#e6e1e9" }
footer = { fg = "#322e41", bg = "#cbc3dc" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#eeb8c9" }
title_warn = { fg = "#cdbdff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e6e1e9" },
    { name = "*/", fg = "#cdbdff" },
]

# : ]]]
