live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#3d375e"
blue = "#587B99"
cyan = "#82e2ff"
green = "#61ffca"
magenta = "#a277ff"
red = "#ff6767"
white = "#FFF4E5"
yellow = "#ffca85"

[colors.normal]
black = "#3d375e"
blue = "#587B99"
cyan = "#82e2ff"
green = "#61ffca"
magenta = "#a277ff"
red = "#ff6767"
white = "#FFF4E5"
yellow = "#ffca85"

[colors.primary]
background = "#140e1a"
foreground = "#edecee"

[colors.selection]
background = '#FFF4E5'
text = '#3d375e'

[colors.cursor]
cursor = '#61ffca'
text = '#FFF4E5'

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Beam"
blinking = "On"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

# [[keyboard.bindings]]
# action = "PasteSelection"
# key = "V"
# mods = "Control"
#
# [[keyboard.bindings]]
# action = "Copy"
# key = "C"
# mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
# auto_scroll = false
history = 5000

[selection]
save_to_clipboard = true

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = false
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 80
lines = 20

[window.padding]
x = 6
y = 6
