config_version = 13

[bar.default]
border = "on_surface"
center = [
    "widget",
    "spacer_2",
    "recorder",
    "mpvpaper",
    "wallhaven",
    "_active_ws",
    "caffeine",
    "workspaces",
    "notifications",
    "_active_ws",
    "todo",
    "clipboard",
    "keybinds",
    "special-workspace",
    "spacer_2"
]
end = [
    "status",
    "_active_ws",
    "network_rx",
    "network_tx",
    "_active_ws",
    "tray",
    "_active_ws",
    "volume",
    "bluetooth",
    "network",
    "_active_ws",
    "date",
    "_active_ws",
    "screen_recorder",
    "session"
]
margin_edge = 0.0
margin_ends = 0.0
padding = 10
radius = 0
radius_bottom_left = 5
radius_bottom_right = 5
start = [
    "control-center",
    "_active_ws",
    "cpu",
    "ram",
    "disc-home",
    "disk-root",
    "_active_ws",
    "group:g1",
    "_active_ws",
    "active_window",
    "toggle",
    "_active_ws",
    "special-workspaces"
]
thickness = 25
widget_spacing = 10

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "gpu", "gpu_vram" ]
    opacity = 1.0
    padding = 6.0

[control_center.calendar]
show_events_card = false
show_week_numbers = true

[desktop_widgets]
enabled = false

[keybinds]
down = [ "Ctrl+n" ]
up = [ "Ctrl+p" ]

[location]
auto_locate = true

[lockscreen]
enabled = false
lock_before_suspend = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [
    "lockscreen-login-box@Unknown-1",
    "lockscreen-login-box@FALLBACK",
    "lockscreen-login-box@DP-3",
    "lockscreen-login-box@DP-1"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 960.0
    cy = 961.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 720.0
    cx = 960.0
    cy = 961.0
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "FALLBACK"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@Unknown-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "Unknown-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@Unknown-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugin_settings."davemhammer/tailscale"]
manager_open_near_click = false
refresh_interval = 5

[plugin_settings."kenn/keybind-cheatsheet"]
cheatsheet_placement = "attached"
cheatsheet_position = "auto"
compositor = "hyprland"
hyprland_parser = "lua"

[plugin_settings."noctalia/mpvpaper"]
video_directory = "~/Wallpaper"

[plugin_settings."noctalia/wallhaven"]
api_key = "CG8wKz123iuIovJ4E69XtghNpikNJXQQ"
download_dir = "~/Wallpaper/Wallhaven"

[plugin_settings."yuuto/arch-updater"]
assume_yes = true
aur_helper = "yay"
auto_check_hours = 1
flatpak_enabled = false
show_activity_graph = true
update_mode = "background"

[plugins]
enabled = [
    "noctalia/screen_recorder",
    "nightwatch75/todo",
    "noctalia/mpvpaper",
    "noctalia/wallhaven",
    "kenn/keybind-cheatsheet",
    "toni/special-workspace",
    "yuuto/arch-updater",
    "maddingo/hypr-layout-switcher",
    "davemhammer/tailscale",
    "jamesfeeder/special-workspaces"
]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    enabled = false
    kind = "path"
    location = "~/Programming/community-plugins"
    name = "Tonigineer"

[shell]
avatar_path = "/home/toni/.face"
corner_radius_scale = 0.5000000074505806
font_family = "Monaspace Krypton"
lang = "en"
password_style = "random"
polkit_agent = true
settings_show_advanced = true
ui_scale = 1.1500000096857548

    [shell.panel]
    launcher_categories = false
    launcher_placement = "attached"
    open_near_click_launcher = true

    [[shell.session.actions]]
    action = "lock"
    command = "/home/toni/.local/share/quickshell-lockscreen/lock.sh"
    countdown_seconds = 2.0
    enabled = true
    shortcut = "l"
    variant = "outline"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "o"
    variant = "default"

    [[shell.session.actions]]
    action = "suspend"
    countdown_seconds = 2.0
    enabled = true
    shortcut = "s"
    variant = "default"

    [[shell.session.actions]]
    action = "command"
    command = "systemctl hibernate"
    countdown_seconds = 2.0
    enabled = true
    glyph = "hibernate"
    label = "Hibernate"
    shortcut = "h"
    variant = "primary"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 2.0
    enabled = true
    shortcut = "r"
    variant = "destructive"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 2.0
    enabled = true
    shortcut = "k"
    variant = "destructive"

[system.monitor]
network_poll_seconds = 1

[theme]
builtin = "Noctalia"
community_palette = "Zenbones"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "muted"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "hyprland", "kitty", "qt" ]
    community_ids = [ "spicetify", "zen-browser", "discord", "neovim", "vscode", "zed", "steam", "lazygit", "yazi", "libreoffice" ]

[wallpaper]
directory = "/home/toni/Wallpaper"
fill_mode = "stretch"
transition_on_startup = true

    [wallpaper.automation]
    order = "alphabetical"

    [wallpaper.default]
    path = "/home/toni/Wallpaper/unix-cloud.jpg"

    [wallpaper.last]
    path = "/home/toni/Wallpaper/unix-cloud.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/toni/Wallpaper/unix-cloud.jpg"

    [wallpaper.monitors.DP-3]
    path = "/home/toni/Wallpaper/unix-cloud.jpg"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/toni/Wallpaper/unix-cloud.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "muted"

[weather]
address = "Markdorf"

[widget._active_ws]
scale = 1.1000000000000001
type = "spacer"

[widget.active_window]
color = "primary"
enabled = false
title_scroll = "always"

[widget.clipboard]
color = "on_surface_variant"
icon_color = "on_surface_variant"

[widget.control-center]
custom_image_colorize = true
glyph = "droplet-search"
icon_color = "error"

[widget.cpu]
show_label = false
show_value = false

[widget.date]
color = "primary"
format = "{:%H:%M %a, %d. %b}"
tooltip_format = "{:%H:%M %a, %d. %b}"

[widget.disc-home]
glyph = "home"
path = "/home"
show_value = false
stat = "disk_used_pct"
type = "sysmon"

[widget.disk-root]
glyph = "devices-pc"
show_value = false
stat = "disk_free_pct"
type = "sysmon"

[widget.gpu]
color = "outline"
show_value = false
stat = "gpu_usage"
type = "sysmon"

[widget.gpu_vram]
color = "outline"
show_value = false
stat = "gpu_vram"
type = "sysmon"

[widget.keybinds]
color = "on_surface_variant"
icon_color = "on_surface_variant"
type = "kenn/keybind-cheatsheet:keybinds"

[widget.mpvpaper]
color = "on_surface_variant"
icon_color = "on_surface_variant"
type = "noctalia/mpvpaper:mpvpaper"

[widget.network]
show_label = false

[widget.network_rx]
capsule_fill = "on_surface"
capsule_opacity = 0.5
capsule_padding = 0
capsule_radius = 20
glyph = "arrow-big-down-lines"
label_min_width = 80
network_speed_unit = "mb"
scale = 0.75
show_label = false
visualization = "none"

[widget.network_tx]
glyph = "arrow-big-up-lines"
label_min_width = 80
network_speed_unit = "mb"
scale = 0.75
show_label = false
visualization = "none"

[widget.notifications]
hide_when_no_unread = true

[widget.ram]
show_label = false
show_value = false

[widget.recorder]
color = "on_surface_variant"
icon_color = "on_surface_variant"
type = "noctalia/screen_recorder:recorder"

[widget.screen_recorder]
copy_to_clipboard = true
frame_rate = 144
hide_inactive = true
script = "scripts/screen_recorder.lua"
type = "scripted"

[widget.session]
color = "error"

[widget.spacer_2]
type = "spacer"

[widget.special-workspace]
hide_when_none = false
type = "toni/special-workspace:special-workspace"

[widget.special-workspaces]
active_style = "ghost"
capsule = true
capsule_fill = "#FFD700"
capsule_foreground = "error"
capsule_padding = 4
color = "error"
enable_scroll = false
font_weight = 600
hide_inactive = true
icon_color = "error"
interactive = false
scale = 0.85000000000000009
type = "jamesfeeder/special-workspaces:special-workspaces"

[widget.status]
scale = 0.80000000000000004
type = "davemhammer/tailscale:status"

[widget.sysmon]
path = "/home"
show_value = false
stat = "gpu_usage"

[widget.temp]
show_label = false

[widget.todo]
color = "on_surface_variant"
icon_color = "on_surface_variant"
type = "nightwatch75/todo:todo"

[widget.toggle]
capsule_foreground = "on_secondary"
capsule_opacity = 0.0
capsule_padding = 9
capsule_radius = 5
color = "#FFD700"
interactive = false
scale = 0.85000000000000009
type = "maddingo/hypr-layout-switcher:toggle"

[widget.tray]
match_adjacent_spacing = true

[widget.volume]
show_label = false

[widget.wallhaven]
color = "on_surface_variant"
icon_color = "on_surface_variant"
type = "noctalia/wallhaven:wallhaven"

[widget.widget]
hide_on_empty = true
type = "yuuto/arch-updater:widget"

[widget.workspaces]
anchor = true
capsule = true
empty_color = "tertiary"
label_source = "name"
scale = 0.94999999999999996