common_text_icons = {
    "playing": "",
    "paused": "",
    "power": "",
    "cpu": "",
    "memory": "",
    "storage": "󰋊",
    "updates": "󱧘",
    "thermometer": "",
}


text_icons = {
    "volume": {
        "overamplified": "󰕾",
        "high": "󰕾",
        "medium": "󰖀",
        "low": "󰕿",
        "muted": "󰝟",
    },
    "brightness": {
        "off": "",
        "low": "",
        "medium": "",
        "high": "",
    },
    "distro": {
        "deepin": "",
        "fedora": "",
        "arch": "",
        "nixos": "",
        "debian": "",
        "opensuse-tumbleweed": "",
        "ubuntu": "",
        "endeavouros": "",
        "manjaro": "",
        "popos": "",
        "garuda": "",
        "zorin": "",
        "mxlinux": "",
        "arcolinux": "",
        "gentoo": "",
        "artix": "",
        "centos": "",
        "hyperbola": "",
        "kubuntu": "",
        "mandriva": "",
        "xerolinux": "",
        "parabola": "",
        "void": "",
        "linuxmint": "",
        "archlabs": "",
        "devuan": "",
        "freebsd": "",
        "openbsd": "",
        "slackware": "",
    },
}

# sourced from wttr.in
WEATHER_SYMBOL_WI_DAY = {
    "Unknown": "",
    "Cloudy": "",
    "Fog": "",
    "HeavyRain": "",
    "HeavyShowers": "",
    "HeavySnow": "",
    "HeavySnowShowers": "",
    "LightRain": "",
    "LightShowers": "",
    "LightSleet": "",
    "LightSleetShowers": "",
    "LightSnow": "",
    "LightSnowShowers": "",
    "PartlyCloudy": "",
    "Sunny": "",
    "ThunderyHeavyRain": "",
    "ThunderyShowers": "",
    "ThunderySnowShowers": "",
    "VeryCloudy": "",
}

WEATHER_SYMBOL_WI_NIGHT = {
    "Unknown": "",
    "Cloudy": "",
    "Fog": "",
    "HeavyRain": "",
    "HeavyShowers": "",
    "HeavySnow": "",
    "HeavySnowShowers": "",
    "LightRain": "",
    "LightShowers": "",
    "LightSleet": "",
    "LightSleetShowers": "",
    "LightSnow": "",
    "LightSnowShowers": "",
    "PartlyCloudy": "",
    "Sunny": "",
    "ThunderyHeavyRain": "",
    "ThunderyShowers": "",
    "ThunderySnowShowers": "",
    "VeryCloudy": "",
}

weather_icons = {
    "113": {
        "description": "Sunny",
        "icon": WEATHER_SYMBOL_WI_DAY["Sunny"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["Sunny"],
        "image": "clear-day",
        "image-night": "clear-night",
    },
    "116": {
        "description": "PartlyCloudy",
        "icon": WEATHER_SYMBOL_WI_DAY["PartlyCloudy"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["PartlyCloudy"],
        "image": "partly-cloudy-day",
        "image-night": "partly-cloudy-night",
    },
    "119": {
        "description": "Cloudy",
        "icon": WEATHER_SYMBOL_WI_DAY["Cloudy"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["Cloudy"],
        "image": "cloudy",
        "image-night": "cloudy",
    },
    "122": {
        "description": "VeryCloudy",
        "icon": WEATHER_SYMBOL_WI_DAY["VeryCloudy"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["VeryCloudy"],
        "image": "cloudy",
        "image-night": "cloudy",
    },
    "143": {
        "description": "Fog",
        "icon": WEATHER_SYMBOL_WI_DAY["Fog"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["Fog"],
        "image": "fog",
        "image-night": "fog-night",
    },
    "176": {
        "description": "LightShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightShowers"],
        "image": "rain",
        "image-night": "rain",
    },
    "179": {
        "description": "LightSleetShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleetShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleetShowers"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "182": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "185": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "200": {
        "description": "ThunderyShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["ThunderyShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["ThunderyShowers"],
        "image": "thunderstorms",
        "image-night": "thunderstorms-night",
    },
    "227": {
        "description": "LightSnow",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSnow"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSnow"],
        "image": "snow",
        "image-night": "snow",
    },
    "230": {
        "description": "HeavySnow",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavySnow"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavySnow"],
        "image": "snow",
        "image-night": "snow",
    },
    "248": {
        "description": "Fog",
        "icon": WEATHER_SYMBOL_WI_DAY["Fog"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["Fog"],
        "image": "fog",
        "image-night": "fog",
    },
    "260": {
        "description": "Fog",
        "icon": WEATHER_SYMBOL_WI_DAY["Fog"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["Fog"],
        "image": "fog",
        "image-night": "fog-night",
    },
    "263": {
        "description": "LightShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightShowers"],
        "image": "rain",
        "image-night": "rain",
    },
    "266": {
        "description": "LightRain",
        "icon": WEATHER_SYMBOL_WI_DAY["LightRain"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightRain"],
        "image": "rain",
        "image-night": "rain",
    },
    "281": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "284": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "293": {
        "description": "LightRain",
        "icon": WEATHER_SYMBOL_WI_DAY["LightRain"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightRain"],
        "image": "rain",
        "image-night": "rain",
    },
    "296": {
        "description": "LightRain",
        "icon": WEATHER_SYMBOL_WI_DAY["LightRain"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightRain"],
        "image": "rain",
        "image-night": "rain",
    },
    "299": {
        "description": "HeavyShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavyShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavyShowers"],
        "image": "rain",
        "image-night": "rain",
    },
    "302": {
        "description": "HeavyRain",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavyRain"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavyRain"],
        "image": "rain",
        "image-night": "rain",
    },
    "305": {
        "description": "HeavyShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavyShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavyShowers"],
        "image": "rain",
        "image-night": "rain",
    },
    "308": {
        "description": "HeavyRain",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavyRain"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavyRain"],
        "image": "rain",
        "image-night": "rain",
    },
    "311": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "314": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "317": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "320": {
        "description": "LightSnow",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSnow"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSnow"],
        "image": "snow",
        "image-night": "snow",
    },
    "323": {
        "description": "LightSnowShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSnowShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSnowShowers"],
        "image": "snow",
        "image-night": "snow",
    },
    "326": {
        "description": "LightSnowShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSnowShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSnowShowers"],
        "image": "snow",
        "image-night": "snow",
    },
    "329": {
        "description": "HeavySnow",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavySnow"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavySnow"],
        "image": "snow",
        "image-night": "snow",
    },
    "332": {
        "description": "HeavySnow",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavySnow"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavySnow"],
        "image": "snow",
        "image-night": "snow",
    },
    "335": {
        "description": "HeavySnowShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavySnowShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavySnowShowers"],
        "image": "snow",
        "image-night": "snow",
    },
    "338": {
        "description": "HeavySnow",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavySnow"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavySnow"],
        "image": "snow",
        "image-night": "snow",
    },
    "350": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "353": {
        "description": "LightShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightShowers"],
        "image": "rain",
        "image-night": "rain",
    },
    "356": {
        "description": "HeavyShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavyShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavyShowers"],
        "image": "rain",
        "image-night": "rain",
    },
    "359": {
        "description": "HeavyRain",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavyRain"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavyRain"],
        "image": "rain",
        "image-night": "rain",
    },
    "362": {
        "description": "LightSleetShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleetShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleetShowers"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "365": {
        "description": "LightSleetShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleetShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleetShowers"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "368": {
        "description": "LightSnowShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSnowShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSnowShowers"],
        "image": "snow",
        "image-night": "snow",
    },
    "371": {
        "description": "HeavySnowShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavySnowShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavySnowShowers"],
        "image": "snow",
        "image-night": "snow",
    },
    "374": {
        "description": "LightSleetShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleetShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleetShowers"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "377": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "386": {
        "description": "ThunderyShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["ThunderyShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["ThunderyShowers"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "389": {
        "description": "ThunderyHeavyRain",
        "icon": WEATHER_SYMBOL_WI_DAY["ThunderyHeavyRain"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["ThunderyHeavyRain"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "392": {
        "description": "ThunderySnowShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["ThunderySnowShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["ThunderySnowShowers"],
        "image": "sleet",
        "image-night": "sleet",
    },
    "395": {
        "description": "HeavySnowShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavySnowShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavySnowShowers"],
        "image": "sleet",
        "image-night": "sleet",
    },
}


icons = {
    "missing": "image-missing-symbolic",
    "nix": {
        "nix": "nix-snowflake-symbolic",
    },
    "app": {
        "terminal": "terminal-symbolic",
    },
    "fallback": {
        "executable": "application-x-executable",
        "notification": "dialog-information-symbolic",
        "video": "video-x-generic-symbolic",
        "audio": "audio-x-generic-symbolic",
        "image": "image-x-generic-symbolic",
        "package": "package-x-generic-symbolic",
    },
    "ui": {
        "window_close": "window-close-symbolic",
        "close": "close-symbolic",
        "colorpicker": "color-select-symbolic",
        "info": "info-symbolic",
        "link": "external-link-symbolic",
        "lock": "system-lock-screen-symbolic",
        "menu": "open-menu-symbolic",
        "refresh": "view-refresh-symbolic",
        "search": "system-search-symbolic",
        "settings": "emblem-system-symbolic",
        "themes": "preferences-desktop-theme-symbolic",
        "tick": "object-select-symbolic",
        "time": "hourglass-symbolic",
        "toolbars": "toolbars-symbolic",
        "warning": "dialog-warning-symbolic",
        "avatar": "avatar-default-symbolic",
        "camera": "camera-photo-symbolic",
        "camera-video": "camera-video-symbolic",
        "arrow": {
            "right": "pan-end-symbolic",
            "left": "pan-start-symbolic",
            "down": "pan-down-symbolic",
            "up": "pan-up-symbolic",
        },
    },
    "audio": {
        "mic": {
            "muted": "microphone-disabled-symbolic",
            "low": "microphone-sensitivity-low-symbolic",
            "medium": "microphone-sensitivity-medium-symbolic",
            "high": "microphone-sensitivity-high-symbolic",
        },
        "volume": {
            "muted": "audio-volume-muted-symbolic",
            "low": "audio-volume-low-symbolic",
            "medium": "audio-volume-medium-symbolic",
            "high": "audio-volume-high-symbolic",
            "overamplified": "audio-volume-overamplified-symbolic",
        },
        "type": {
            "headset": "audio-headphones-symbolic",
            "speaker": "audio-speakers-symbolic",
            "card": "audio-card-symbolic",
        },
        "mixer": "mixer-symbolic",
    },
    "powerprofiles": {
        "balanced": "power-profile-balanced-symbolic",
        "power-saver": "power-profile-power-saver-symbolic",
        "performance": "power-profile-performance-symbolic",
    },
    "battery": {
        "charging": "battery-flash-symbolic",
        "full": "battery-full-charged-symbolic",
        "full-charging": "battery-full-charging-symbolic",
        "full-discharging": "battery-full-discharging-symbolic",
        "discharging": "battery-empty-symbolic",
        "empty": "battery-empty-symbolic",
        "charging-unknown": "battery-charging-symbolic",
        "unknown": "battery-missing-symbolic",
    },
    "bluetooth": {
        "enabled": "bluetooth-active-symbolic",
        "disabled": "bluetooth-disabled-symbolic",
    },
    "brightness": {
        "indicator": "display-brightness-symbolic",
        "keyboard": "keyboard-brightness-symbolic",
        "screen": "display-brightness-symbolic",
        "low": "display-brightness-low-symbolic",
        "medium": "display-brightness-medium-symbolic",
        "high": "display-brightness-high-symbolic",
        "off": "display-brightness-off-symbolic",
    },
    "powermenu": {
        "sleep": "system-suspend-symbolic",
        "reboot": "system-reboot-symbolic",
        "logout": "system-log-out-symbolic",
        "shutdown": "system-shutdown-symbolic",
    },
    "recorder": {
        "recording": "media-record-symbolic",
        "stopped": "media-record-symbolic",
    },
    "notifications": {
        "noisy": "org.gnome.Settings-notifications-symbolic",
        "silent": "notifications-disabled-symbolic",
        "message": "chat-bubbles-symbolic",
    },
    "trash": {
        "full": "user-trash-full-symbolic",
        "empty": "user-trash-symbolic",
    },
    "network": {
        "wifi": {
            "generic": "network-wireless-symbolic",
            "connected": "network-wireless-connected-symbolic",
            "disconnected": "network-wireless-disconnected-symbolic",
            "connecting": "network-wireless-acquiring-symbolic",
            "disabled": "network-wireless-disabled-symbolic",
        },
        "ethernet": {
            "connected": "network-wired-connected-symbolic",
            "disconnected": "network-wired-disconnected-symbolic",
            "connecting": "network-wired-acquiring-symbolic",
            "disabled": "network-wired-disabled-symbolic",
        },
        "vpn": {
            "enabled": "network-vpn-symbolic",
            "disabled": "network-vpn-off-symbolic",
        },
    },
    "mpris": {
        "shuffle": {
            "enabled": "media-playlist-shuffle-symbolic",
            "disabled": "media-playlist-consecutive-symbolic",
        },
        "loop": {
            "none": "media-playlist-repeat-symbolic",
            "track": "media-playlist-repeat-song-symbolic",
            "playlist": "media-playlist-repeat-symbolic",
        },
        "playing": "media-playback-pause-symbolic",
        "paused": "media-playback-start-symbolic",
        "stopped": "media-playback-start-symbolic",
        "prev": "media-skip-backward-symbolic",
        "next": "media-skip-forward-symbolic",
    },
    "system": {
        "cpu": "org.gnome.SystemMonitor-symbolic",
        "ram": "drive-harddisk-solidstate-symbolic",
        "temp": "temperature-symbolic",
    },
    "color": {
        "dark": "dark-mode-symbolic",
        "light": "light-mode-symbolic",
    },
}
